version: '3'
services: 
    flask:
        build: .
        # command: python -V
        environment: 
            - FLASK_APP=hello
            - FLASK_DEBUG=1
            - PYTHONUNBUFFERED=True
        # command: flask run --host=0.0.0.0
        # gunicorn -w 4 -b 127.0.0.1:4000 myproject:app
        command: gunicorn -w 1 -b 0.0.0.0:5000 hello:app --reload
        ports:
            - "5000:5000"
        volumes:
            - ./:/root